server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Logging
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.web=INFO
