spring.application.name=DeliveryTourOptimizer
# Server
server.port=8080

# Active profile
spring.profiles.active=dev

# Common JPA and Logging settings
spring.jpa.open-in-view=false
logging.level.org.springframework=INFO